// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/jenkins-x/jx-preview/pkg/apis/preview/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePreviews implements PreviewInterface
type FakePreviews struct {
	Fake *FakePreviewV1alpha1
	ns   string
}

var previewsResource = schema.GroupVersionResource{Group: "preview.jenkins.io", Version: "v1alpha1", Resource: "previews"}

var previewsKind = schema.GroupVersionKind{Group: "preview.jenkins.io", Version: "v1alpha1", Kind: "Preview"}

// Get takes name of the preview, and returns the corresponding preview object, and an error if there is any.
func (c *FakePreviews) Get(name string, options v1.GetOptions) (result *v1alpha1.Preview, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(previewsResource, c.ns, name), &v1alpha1.Preview{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Preview), err
}

// List takes label and field selectors, and returns the list of Previews that match those selectors.
func (c *FakePreviews) List(opts v1.ListOptions) (result *v1alpha1.PreviewList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(previewsResource, previewsKind, c.ns, opts), &v1alpha1.PreviewList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PreviewList{ListMeta: obj.(*v1alpha1.PreviewList).ListMeta}
	for _, item := range obj.(*v1alpha1.PreviewList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested previews.
func (c *FakePreviews) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(previewsResource, c.ns, opts))

}

// Create takes the representation of a preview and creates it.  Returns the server's representation of the preview, and an error, if there is any.
func (c *FakePreviews) Create(preview *v1alpha1.Preview) (result *v1alpha1.Preview, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(previewsResource, c.ns, preview), &v1alpha1.Preview{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Preview), err
}

// Update takes the representation of a preview and updates it. Returns the server's representation of the preview, and an error, if there is any.
func (c *FakePreviews) Update(preview *v1alpha1.Preview) (result *v1alpha1.Preview, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(previewsResource, c.ns, preview), &v1alpha1.Preview{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Preview), err
}

// Delete takes name of the preview and deletes it. Returns an error if one occurs.
func (c *FakePreviews) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(previewsResource, c.ns, name), &v1alpha1.Preview{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePreviews) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(previewsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.PreviewList{})
	return err
}

// Patch applies the patch and returns the patched preview.
func (c *FakePreviews) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Preview, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(previewsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Preview{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Preview), err
}
