// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/jenkins-x/jx-preview/pkg/client/clientset/versioned/typed/preview/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakePreviewV1alpha1 struct {
	*testing.Fake
}

func (c *FakePreviewV1alpha1) Previews(namespace string) v1alpha1.PreviewInterface {
	return &FakePreviews{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakePreviewV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
