// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	previewv1alpha1 "github.com/jenkins-x/jx-preview/pkg/apis/preview/v1alpha1"
	versioned "github.com/jenkins-x/jx-preview/pkg/client/clientset/versioned"
	internalinterfaces "github.com/jenkins-x/jx-preview/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/jenkins-x/jx-preview/pkg/client/listers/preview/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PreviewInformer provides access to a shared informer and lister for
// Previews.
type PreviewInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PreviewLister
}

type previewInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPreviewInformer constructs a new informer for Preview type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPreviewInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPreviewInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPreviewInformer constructs a new informer for Preview type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPreviewInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PreviewV1alpha1().Previews(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PreviewV1alpha1().Previews(namespace).Watch(options)
			},
		},
		&previewv1alpha1.Preview{},
		resyncPeriod,
		indexers,
	)
}

func (f *previewInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPreviewInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *previewInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&previewv1alpha1.Preview{}, f.defaultInformer)
}

func (f *previewInformer) Lister() v1alpha1.PreviewLister {
	return v1alpha1.NewPreviewLister(f.Informer().GetIndexer())
}
