// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// PreviewListerExpansion allows custom methods to be added to
// PreviewLister.
type PreviewListerExpansion interface{}

// PreviewNamespaceListerExpansion allows custom methods to be added to
// PreviewNamespaceLister.
type PreviewNamespaceListerExpansion interface{}
